var express = require('express')
var path = require('path')
var app = express()
var router = require('./files/router')
var bodyParser = require('body-parser')
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.engine('html', require('express-art-template'))
app.use('/public/', express.static(path.join(__dirname, './public/')))
app.use('/node_modules', express.static(path.join(__dirname, '../node_modules/')))
app.use(router)
app.listen(2333, function () {
    console.log('Server is running at port 2333')
})
